# Generated by Django 5.0.4 on 2024-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_organization_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
