# Generated by Django 5.0.4 on 2024-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_organization_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_link', models.CharField(max_length=100)),
            ],
        ),
    ]
