# Generated by Django 5.0.4 on 2024-05-07 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_link',
            field=models.CharField(max_length=1000),
        ),
    ]
