# Generated by Django 5.0.4 on 2024-05-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_products_company_id_products_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='org_id',
            new_name='org',
        ),
    ]
