# Generated by Django 5.0.4 on 2024-05-08 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_org_id_products_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.organization'),
        ),
    ]
